CREATE TABLE IF NOT EXISTS `tbl_psipop` (
    `psipop_id`     INT AUTO_INCREMENT PRIMARY KEY,
    `aa_division`	VARCHAR(255) NOT NULL,
    `aa_no`       INT NOT NULL,
    `item_no`	    VARCHAR(255) NOT NULL,
    `position`    VARCHAR(255) NOT NULL,
    `salary_grade` TINYINT NOT NULL,
    `sg_no`       TINYINT NOT NULL,
    `authorized`  INT NOT NULL,
    `actual`      INT NOT NULL,
    `step`        TINYINT NOT NULL,
    `area_code`   VARCHAR(255) NOT NULL,
    `area_type`   VARCHAR(10) NOT NULL,
    `psipop_level` VARCHAR(10) NOT NULL,
    `name_of_incumbent` VARCHAR(255) NOT NULL,
    `sex`         VARCHAR(10) NOT NULL,
    `date_of_birth` DATE NOT NULL, 
    `tin`         VARCHAR(255) NOT NULL,
    `date_of_original_appointment` DATE NOT NULL,
    `date_of_last_promotion` DATE NOT NULL,
    `psipop_status` VARCHAR(10) NOT NULL,
    `technical`   VARCHAR(10) NOT NULL,
    `non_executive_managerial` VARCHAR(10) NOT NULL,
    `executive_managerial` VARCHAR(10) NOT NULL,
    `presidential_appointee` VARCHAR(10) NOT NULL,
    `civil_service_eligibility` VARCHAR(255) NOT NULL,
    `educational_attainment` VARCHAR(255) NOT NULL,
    `cs_professional` VARCHAR(255) NOT NULL,
    `cs_sub_professional` VARCHAR(255) NOT NULL,
    `ra_1080`     VARCHAR(255) NOT NULL,
    `pd_907`      VARCHAR(255) NOT NULL,
    `mc_11`       VARCHAR(255) NOT NULL,
    `others_specify` VARCHAR(255) NOT NULL,
    `ceso_rank`   VARCHAR(255) NOT NULL,
    `ces_eligible` VARCHAR(255) NOT NULL,
    `csee`        VARCHAR(255) NOT NULL,
    `doctoral`    VARCHAR(255) NOT NULL,
    `with_units_in_doctoral` VARCHAR(255) NOT NULL,
    `masteral`    VARCHAR(255) NOT NULL,
    `with_units_in_masteral` VARCHAR(255) NOT NULL,
    `diploma_course` VARCHAR(255) NOT NULL,
    `college_graduate` VARCHAR(255) NOT NULL,
    `college_under_graduate` VARCHAR(255) NOT NULL,
    `vocatioanal` VARCHAR(255) NOT NULL,
    `secondary_school` VARCHAR(255) NOT NULL,
    `secondary_under_graduate` VARCHAR(255) NOT NULL,
    `elementary` VARCHAR(255) NOT NULL,
    `place_of_assignment_of_position_per_plantilla` VARCHAR(255) NOT NULL,
    `Present_place_of_assignment_or_designation`	 VARCHAR(255) NOT NULL,
    `remarks` VARCHAR(255) NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)  ENGINE=INNODB;

/*columns migration*/
aa_division,aa_no,item_no,position,salary_grade,sg_no,authorized,actual,step,area_code,area_type,psipop_level,name_of_incumbent,sex,date_of_birth,tin,date_of_original_appointment,date_of_last_promotion,psipop_status,technical,non_executive_managerial,executive_managerial,presidential_appointee,civil_service_eligibility,educational_attainment,cs_professional,cs_sub_professional,ra_1080,pd_907,mc_11,others_specify,ceso_rank,ces_eligible,csee,doctoral,with_units_in_doctoral,masteral,with_units_in_masteral,diploma_course,college_graduate,college_under_graduate,vocatioanal,secondary_school,secondary_under_graduate,elementary,place_of_assignment_of_position_per_plantilla,Present_place_of_assignment_or_designation,remarks